server:
  port: 8085
spring:
  profiles:
    active: db-persist
welcome:
  message: The Spring Boot application and Rest Controller is working properly!
token:
  secret: ${SECRET_KEY}
  validity_in_seconds: 7200 # two hours

---

spring:
  config:
    activate:
      on-profile: db-persist
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
